---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: labs-dev

bases:
- ../base

patchesStrategicMerge:
- postgresql-data-claim.yaml
- postgresql-slave-deploymentconfig.yaml
