kind: Deployment
apiVersion: apps/v1
metadata:
  name: curriki-postgres-exporter
  labels:
    app: curriki-postgres-exporter
    app.kubernetes.io/component: curriki-postgres-exporter
    app.kubernetes.io/instance: curriki-postgres-exporter
spec:
  template:
    metadata:
      labels:
        app: curriki-postgres-exporter
        deploymentconfig: curriki-postgres-exporter
      annotations:
        openshift.io/generated-by: OpenShiftWebConsole
    spec:
      containers:
        - name: curriki-postgres-exporter
          env:
            - name: DATA_SOURCE_NAME
              value: >-
                postgresql://pguser:password@postgresql-master.labs-dev.svc.cluster.local:5432/currikidb?sslmode=disable
