builds:
  enabled: true
  git_url: https://github.com/imcoder001/curriki-docker
istag:
  enabled: true
# OpenShift objects
route: true
replicas: 1
image_repository: quay.io
image_name: curriki-admin
image_namespace: curriki
image_version: latest
