---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: labs-test

resources:
- curriki-api-sealedsecret.yaml
- curriki-api-echo-server-sealedsecret.yaml
- curriki-tsugi-env-sealedsecret.yaml
- curriki-api-tls-sealedsecret.yaml
- curriki-ui-tls-sealedsecret.yaml
