apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: curriki-ui
    app.kubernetes.io/component: curriki-ui
    app.kubernetes.io/instance: curriki-ui
    app.kubernetes.io/part-of: curriki
  name: curriki-ui
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: curriki-ui:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    contextDir: /
    git:
      uri: https://github.com/imcoder001/curriki-docker
    type: Git
  strategy:
    dockerStrategy:
      dockerfilePath: Dockerfile.client
    type: Docker
  successfulBuildsHistoryLimit: 5
  triggers:
  - generic:
      secretReference:
        name: curriki-ui-generic-webhook-secret
    type: Generic
  - github:
      secretReference:
        name: curriki-ui-github-webhook-secret
    type: GitHub
  - type: ConfigChange
