---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: labs-ci-cd

resources:
- git-auth-sealedsecret.yaml
- argocd-token-sealedsecret.yaml
- nexus-password-sealedsecret.yaml
