---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- postgresql-data-claim.yaml
- postgresql-master-service.yaml
- postgresql-slave-deploymentconfig.yaml
- postgresql-slave-service.yaml
- postgresql-master-deploymentconfig.yaml
- api-database-load-job.yaml
