---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- pgadmin.yaml
#- postgresql-data-claim.yaml
#- postgresql-master-service.yaml
#- postgresql-slave-deploymentconfig.yaml
#- postgresql-slave-service.yaml
#- postgresql-master-deploymentconfig.yaml
- api-database-load-job.yaml
- postgresql-exporter-deployment.yaml
- postgresql-exporter-service-monitoring.yaml
- postgresql-exporter-service.yaml
- postgresql-zolando-configmap.yaml
- postgresql-zolando-operator.yaml
- postgresql-zolando-zolando-service.yaml
- postgresql-zolando-service-account.yaml