---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
#- operator-scc
#- dev-cluster
#- operator-dev-cluster
- operator-labs-dev
- operator-labs-test
- labs-dev
- labs-test
- operator-labs-staging
- labs-staging
